name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Create or update release pull request
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ github.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
