name: Validate PR title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate Conventional Commit title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          types: |
            feat
            fix
            deps
            docs
            refactor
            test
            chore
            ci
            build
            revert
          subjectPattern: '^[a-z].+$'
          subjectPatternError: >-
            The pull request title description must start with a lowercase
            character. Received "{subject}" in "{title}".
